receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch: {}

exporters:
  # Send traces to Jaeger using OTLP gRPC
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: normal
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8889    # Prometheus scrapes http://otel-collector:8889/metrics

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
