// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/business/v1/business.proto

package business_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_AGENT  EntityType = 0
	EntityType_FILING EntityType = 1
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "AGENT",
		1: "FILING",
	}
	EntityType_value = map[string]int32{
		"AGENT":  0,
		"FILING": 1,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_business_v1_business_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_api_business_v1_business_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{0}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityName    string                 `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	EntityOrg     string                 `protobuf:"bytes,4,opt,name=entity_org,json=entityOrg,proto3" json:"entity_org,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	AgentType     string                 `protobuf:"bytes,7,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	PositionType  string                 `protobuf:"bytes,8,opt,name=position_type,json=positionType,proto3" json:"position_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_api_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Agent) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *Agent) GetEntityOrg() string {
	if x != nil {
		return x.EntityOrg
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Agent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *Agent) GetPositionType() string {
	if x != nil {
		return x.PositionType
	}
	return ""
}

type Filing struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId            string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityName          string                 `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	InitialFilingDate   uint64                 `protobuf:"varint,4,opt,name=initial_filing_date,json=initialFilingDate,proto3" json:"initial_filing_date,omitempty"`
	Jurisdiction        string                 `protobuf:"bytes,5,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Sos                 string                 `protobuf:"bytes,7,opt,name=sos,proto3" json:"sos,omitempty"`
	Type                string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	FilingType          string                 `protobuf:"bytes,9,opt,name=filing_type,json=filingType,proto3" json:"filing_type,omitempty"`
	ForeignName         string                 `protobuf:"bytes,10,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	Ftb                 string                 `protobuf:"bytes,11,opt,name=ftb,proto3" json:"ftb,omitempty"`
	Vcfcf               string                 `protobuf:"bytes,12,opt,name=vcfcf,proto3" json:"vcfcf,omitempty"`
	SuspensionDate      uint64                 `protobuf:"varint,13,opt,name=suspension_date,json=suspensionDate,proto3" json:"suspension_date,omitempty"`
	LastFiledNum        string                 `protobuf:"bytes,14,opt,name=last_filed_num,json=lastFiledNum,proto3" json:"last_filed_num,omitempty"`
	LastFiledDate       uint64                 `protobuf:"varint,15,opt,name=last_filed_date,json=lastFiledDate,proto3" json:"last_filed_date,omitempty"`
	PrincipalAddress    string                 `protobuf:"bytes,16,opt,name=principal_address,json=principalAddress,proto3" json:"principal_address,omitempty"`
	MailingAddress      string                 `protobuf:"bytes,17,opt,name=mailing_address,json=mailingAddress,proto3" json:"mailing_address,omitempty"`
	LocalAddress        string                 `protobuf:"bytes,18,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	ManagementStructure string                 `protobuf:"bytes,19,opt,name=management_structure,json=managementStructure,proto3" json:"management_structure,omitempty"`
	BusinessType        string                 `protobuf:"bytes,20,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Filing) Reset() {
	*x = Filing{}
	mi := &file_api_business_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filing) ProtoMessage() {}

func (x *Filing) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filing.ProtoReflect.Descriptor instead.
func (*Filing) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *Filing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Filing) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Filing) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *Filing) GetInitialFilingDate() uint64 {
	if x != nil {
		return x.InitialFilingDate
	}
	return 0
}

func (x *Filing) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *Filing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Filing) GetSos() string {
	if x != nil {
		return x.Sos
	}
	return ""
}

func (x *Filing) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Filing) GetFilingType() string {
	if x != nil {
		return x.FilingType
	}
	return ""
}

func (x *Filing) GetForeignName() string {
	if x != nil {
		return x.ForeignName
	}
	return ""
}

func (x *Filing) GetFtb() string {
	if x != nil {
		return x.Ftb
	}
	return ""
}

func (x *Filing) GetVcfcf() string {
	if x != nil {
		return x.Vcfcf
	}
	return ""
}

func (x *Filing) GetSuspensionDate() uint64 {
	if x != nil {
		return x.SuspensionDate
	}
	return 0
}

func (x *Filing) GetLastFiledNum() string {
	if x != nil {
		return x.LastFiledNum
	}
	return ""
}

func (x *Filing) GetLastFiledDate() uint64 {
	if x != nil {
		return x.LastFiledDate
	}
	return 0
}

func (x *Filing) GetPrincipalAddress() string {
	if x != nil {
		return x.PrincipalAddress
	}
	return ""
}

func (x *Filing) GetMailingAddress() string {
	if x != nil {
		return x.MailingAddress
	}
	return ""
}

func (x *Filing) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *Filing) GetManagementStructure() string {
	if x != nil {
		return x.ManagementStructure
	}
	return ""
}

func (x *Filing) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

type AddEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type          EntityType             `protobuf:"varint,2,opt,name=type,proto3,enum=business.v1.EntityType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityRequest) Reset() {
	*x = AddEntityRequest{}
	mi := &file_api_business_v1_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityRequest) ProtoMessage() {}

func (x *AddEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityRequest.ProtoReflect.Descriptor instead.
func (*AddEntityRequest) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{2}
}

func (x *AddEntityRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AddEntityRequest) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_AGENT
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EntityType             `protobuf:"varint,2,opt,name=type,proto3,enum=business.v1.EntityType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_api_business_v1_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{3}
}

func (x *EntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityRequest) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_AGENT
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_business_v1_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type EntityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Types that are valid to be assigned to TestOneof:
	//
	//	*EntityResponse_Agent
	//	*EntityResponse_Filing
	TestOneof     isEntityResponse_TestOneof `protobuf_oneof:"test_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	mi := &file_api_business_v1_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{5}
}

func (x *EntityResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EntityResponse) GetTestOneof() isEntityResponse_TestOneof {
	if x != nil {
		return x.TestOneof
	}
	return nil
}

func (x *EntityResponse) GetAgent() *Agent {
	if x != nil {
		if x, ok := x.TestOneof.(*EntityResponse_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *EntityResponse) GetFiling() *Filing {
	if x != nil {
		if x, ok := x.TestOneof.(*EntityResponse_Filing); ok {
			return x.Filing
		}
	}
	return nil
}

type isEntityResponse_TestOneof interface {
	isEntityResponse_TestOneof()
}

type EntityResponse_Agent struct {
	Agent *Agent `protobuf:"bytes,2,opt,name=agent,proto3,oneof"`
}

type EntityResponse_Filing struct {
	Filing *Filing `protobuf:"bytes,3,opt,name=filing,proto3,oneof"`
}

func (*EntityResponse_Agent) isEntityResponse_TestOneof() {}

func (*EntityResponse_Filing) isEntityResponse_TestOneof() {}

type StreamEntityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TestOneof:
	//
	//	*StreamEntityResponse_EntityResponse
	//	*StreamEntityResponse_Error
	TestOneof     isStreamEntityResponse_TestOneof `protobuf_oneof:"test_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntityResponse) Reset() {
	*x = StreamEntityResponse{}
	mi := &file_api_business_v1_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntityResponse) ProtoMessage() {}

func (x *StreamEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_business_v1_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntityResponse.ProtoReflect.Descriptor instead.
func (*StreamEntityResponse) Descriptor() ([]byte, []int) {
	return file_api_business_v1_business_proto_rawDescGZIP(), []int{6}
}

func (x *StreamEntityResponse) GetTestOneof() isStreamEntityResponse_TestOneof {
	if x != nil {
		return x.TestOneof
	}
	return nil
}

func (x *StreamEntityResponse) GetEntityResponse() *EntityResponse {
	if x != nil {
		if x, ok := x.TestOneof.(*StreamEntityResponse_EntityResponse); ok {
			return x.EntityResponse
		}
	}
	return nil
}

func (x *StreamEntityResponse) GetError() string {
	if x != nil {
		if x, ok := x.TestOneof.(*StreamEntityResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isStreamEntityResponse_TestOneof interface {
	isStreamEntityResponse_TestOneof()
}

type StreamEntityResponse_EntityResponse struct {
	EntityResponse *EntityResponse `protobuf:"bytes,1,opt,name=entity_response,json=entityResponse,proto3,oneof"`
}

type StreamEntityResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StreamEntityResponse_EntityResponse) isStreamEntityResponse_TestOneof() {}

func (*StreamEntityResponse_Error) isStreamEntityResponse_TestOneof() {}

var File_api_business_v1_business_proto protoreflect.FileDescriptor

const file_api_business_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/business/v1/business.proto\x12\vbusiness.v1\"\xe6\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_name\x18\x03 \x01(\tR\n" +
	"entityName\x12\x1d\n" +
	"\n" +
	"entity_org\x18\x04 \x01(\tR\tentityOrg\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"agent_type\x18\a \x01(\tR\tagentType\x12#\n" +
	"\rposition_type\x18\b \x01(\tR\fpositionType\"\x9e\x05\n" +
	"\x06Filing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_name\x18\x03 \x01(\tR\n" +
	"entityName\x12.\n" +
	"\x13initial_filing_date\x18\x04 \x01(\x04R\x11initialFilingDate\x12\"\n" +
	"\fjurisdiction\x18\x05 \x01(\tR\fjurisdiction\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03sos\x18\a \x01(\tR\x03sos\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x1f\n" +
	"\vfiling_type\x18\t \x01(\tR\n" +
	"filingType\x12!\n" +
	"\fforeign_name\x18\n" +
	" \x01(\tR\vforeignName\x12\x10\n" +
	"\x03ftb\x18\v \x01(\tR\x03ftb\x12\x14\n" +
	"\x05vcfcf\x18\f \x01(\tR\x05vcfcf\x12'\n" +
	"\x0fsuspension_date\x18\r \x01(\x04R\x0esuspensionDate\x12$\n" +
	"\x0elast_filed_num\x18\x0e \x01(\tR\flastFiledNum\x12&\n" +
	"\x0flast_filed_date\x18\x0f \x01(\x04R\rlastFiledDate\x12+\n" +
	"\x11principal_address\x18\x10 \x01(\tR\x10principalAddress\x12'\n" +
	"\x0fmailing_address\x18\x11 \x01(\tR\x0emailingAddress\x12#\n" +
	"\rlocal_address\x18\x12 \x01(\tR\flocalAddress\x121\n" +
	"\x14management_structure\x18\x13 \x01(\tR\x13managementStructure\x12#\n" +
	"\rbusiness_type\x18\x14 \x01(\tR\fbusinessType\"\xbd\x01\n" +
	"\x10AddEntityRequest\x12A\n" +
	"\x06fields\x18\x01 \x03(\v2).business.v1.AddEntityRequest.FieldsEntryR\x06fields\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.business.v1.EntityTypeR\x04type\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\rEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.business.v1.EntityTypeR\x04type\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x89\x01\n" +
	"\x0eEntityResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12*\n" +
	"\x05agent\x18\x02 \x01(\v2\x12.business.v1.AgentH\x00R\x05agent\x12-\n" +
	"\x06filing\x18\x03 \x01(\v2\x13.business.v1.FilingH\x00R\x06filingB\f\n" +
	"\n" +
	"test_oneof\"\x84\x01\n" +
	"\x14StreamEntityResponse\x12F\n" +
	"\x0fentity_response\x18\x01 \x01(\v2\x1b.business.v1.EntityResponseH\x00R\x0eentityResponse\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\f\n" +
	"\n" +
	"test_oneof*#\n" +
	"\n" +
	"EntityType\x12\t\n" +
	"\x05AGENT\x10\x00\x12\n" +
	"\n" +
	"\x06FILING\x10\x012\xc7\x02\n" +
	"\bBusiness\x12I\n" +
	"\tAddEntity\x12\x1d.business.v1.AddEntityRequest\x1a\x1b.business.v1.EntityResponse\"\x00\x12I\n" +
	"\fDeleteEntity\x12\x1a.business.v1.EntityRequest\x1a\x1b.business.v1.DeleteResponse\"\x00\x12F\n" +
	"\tGetEntity\x12\x1a.business.v1.EntityRequest\x1a\x1b.business.v1.EntityResponse\"\x00\x12]\n" +
	"\x13AddBusinessEntities\x12\x1d.business.v1.AddEntityRequest\x1a!.business.v1.StreamEntityResponse\"\x00(\x010\x01B8Z6github.com/hankgalt/workflow-scheduler/api/business_v1b\x06proto3"

var (
	file_api_business_v1_business_proto_rawDescOnce sync.Once
	file_api_business_v1_business_proto_rawDescData []byte
)

func file_api_business_v1_business_proto_rawDescGZIP() []byte {
	file_api_business_v1_business_proto_rawDescOnce.Do(func() {
		file_api_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_business_v1_business_proto_rawDesc), len(file_api_business_v1_business_proto_rawDesc)))
	})
	return file_api_business_v1_business_proto_rawDescData
}

var file_api_business_v1_business_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_business_v1_business_proto_goTypes = []any{
	(EntityType)(0),              // 0: business.v1.EntityType
	(*Agent)(nil),                // 1: business.v1.Agent
	(*Filing)(nil),               // 2: business.v1.Filing
	(*AddEntityRequest)(nil),     // 3: business.v1.AddEntityRequest
	(*EntityRequest)(nil),        // 4: business.v1.EntityRequest
	(*DeleteResponse)(nil),       // 5: business.v1.DeleteResponse
	(*EntityResponse)(nil),       // 6: business.v1.EntityResponse
	(*StreamEntityResponse)(nil), // 7: business.v1.StreamEntityResponse
	nil,                          // 8: business.v1.AddEntityRequest.FieldsEntry
}
var file_api_business_v1_business_proto_depIdxs = []int32{
	8,  // 0: business.v1.AddEntityRequest.fields:type_name -> business.v1.AddEntityRequest.FieldsEntry
	0,  // 1: business.v1.AddEntityRequest.type:type_name -> business.v1.EntityType
	0,  // 2: business.v1.EntityRequest.type:type_name -> business.v1.EntityType
	1,  // 3: business.v1.EntityResponse.agent:type_name -> business.v1.Agent
	2,  // 4: business.v1.EntityResponse.filing:type_name -> business.v1.Filing
	6,  // 5: business.v1.StreamEntityResponse.entity_response:type_name -> business.v1.EntityResponse
	3,  // 6: business.v1.Business.AddEntity:input_type -> business.v1.AddEntityRequest
	4,  // 7: business.v1.Business.DeleteEntity:input_type -> business.v1.EntityRequest
	4,  // 8: business.v1.Business.GetEntity:input_type -> business.v1.EntityRequest
	3,  // 9: business.v1.Business.AddBusinessEntities:input_type -> business.v1.AddEntityRequest
	6,  // 10: business.v1.Business.AddEntity:output_type -> business.v1.EntityResponse
	5,  // 11: business.v1.Business.DeleteEntity:output_type -> business.v1.DeleteResponse
	6,  // 12: business.v1.Business.GetEntity:output_type -> business.v1.EntityResponse
	7,  // 13: business.v1.Business.AddBusinessEntities:output_type -> business.v1.StreamEntityResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_business_v1_business_proto_init() }
func file_api_business_v1_business_proto_init() {
	if File_api_business_v1_business_proto != nil {
		return
	}
	file_api_business_v1_business_proto_msgTypes[5].OneofWrappers = []any{
		(*EntityResponse_Agent)(nil),
		(*EntityResponse_Filing)(nil),
	}
	file_api_business_v1_business_proto_msgTypes[6].OneofWrappers = []any{
		(*StreamEntityResponse_EntityResponse)(nil),
		(*StreamEntityResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_business_v1_business_proto_rawDesc), len(file_api_business_v1_business_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_business_v1_business_proto_goTypes,
		DependencyIndexes: file_api_business_v1_business_proto_depIdxs,
		EnumInfos:         file_api_business_v1_business_proto_enumTypes,
		MessageInfos:      file_api_business_v1_business_proto_msgTypes,
	}.Build()
	File_api_business_v1_business_proto = out.File
	file_api_business_v1_business_proto_goTypes = nil
	file_api_business_v1_business_proto_depIdxs = nil
}
