services:
  batch-worker:
    image: batch-worker:dev-${IMG_TAG}
    platform: linux/arm64
    container_name: batch-worker
    build:
      context: ../..
      dockerfile: cmd/workers/batch/Dockerfile
      args:
        GO_VERSION: "1.24.7"
    env_file:
      - ../../env/batch.env
    volumes:
      - ../../cmd/workers/batch/creds:/app/creds:ro
      - ../../cmd/workers/batch/data:/app/data:rw
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    networks:
      schenet:

networks:
  schenet:
    external: true