
services:
  
  scheduler-mongo:
    image: mongo:8.0
    container_name: scheduler-mongo
    env_file:
      - mongo.env
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - scheduler-mongo-data:/data/db
    command: ["mongod", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - schenet
  
  scheduler-mongo-rep-1:
    image: mongo:8.0
    container_name: scheduler-mongo-rep-1
    env_file:
      - mongo.env
    ports:
      - 27118:27017
    restart: always
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - scheduler-mongo-rep-1-data:/data/db
    command: ["mongod", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - schenet
  
  scheduler-mongo-rep-2:
    image: mongo:8.0
    container_name: scheduler-mongo-rep-2
    env_file:
      - mongo.env
    ports:
      - 27119:27017
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - scheduler-mongo-rep-2-data:/data/db
    restart: always
    command: ["mongod", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
    networks:
      - schenet

networks:
  schenet:
    external: true

volumes:
  scheduler-mongo-data:
  scheduler-mongo-rep-1-data:
  scheduler-mongo-rep-2-data: