services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=15d"]
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - schenet

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - schenet

  # Optional: Jaeger all-in-one (receives OTLP gRPC on 4317)
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # JaegerUI
      # - "4317:4317"
      # - "4318:4318"
    networks:
      - schenet

  # Recommended: OTEL Collector in front of Jaeger/Tempo/etc.
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"     # OTLP gRPC (from your app)
      - "8889:8889"     # Collector metrics
    depends_on:
      - jaeger
    networks:
      - schenet

networks:
  schenet:
    external: true
