version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      - schenet
  # mysql:
  #   platform: linux/x86_64
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=root"
  #   volumes:
  #     - ./data/mysql/:/var/lib/mysql
  elasticsearch:
    image: opensearchproject/opensearch:1.3.6
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
    networks:
      - schenet
  elasticsearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.6
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://elasticsearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - schenet
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - schenet
  zookeeper:
    platform: linux/x86_64
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - schenet
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-cadence.yml'
    ports:
      - '9090:9090'
    networks:
      - schenet
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - schenet
  cadence:
    platform: linux/x86_64
    image: ubercadence/server:master-auto-setup
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8002:8002"
     - "8003:8003"
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
     - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      # - "DB=mysql"
      # - "MYSQL_USER=root"
      # - "MYSQL_PWD=root"
      # - "MYSQL_SEEDS=mysql"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      # - mysql
      - prometheus
    networks:
      - schenet
  cadence-web:
    platform: linux/x86_64
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
    networks:
      - schenet
  grafana:
    image: grafana/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - schenet

networks:
  schenet:
    driver: bridge

