
services:
  mongodb-scheduler:
    container_name: mongodb-scheduler
    image: mongo:7.0
    ports:
      - 27117:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - schenet
  mongodb-scheduler-rep-0:
    container_name: mongodb-scheduler-rep-0
    image: mongo:7.0
    ports:
      - 27118:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - schenet
  mongodb-scheduler-rep-1:
    container_name: mongodb-scheduler-rep-1
    image: mongo:7.0
    ports:
      - 27119:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    networks:
      - schenet

networks:
  schenet:
    external: true

volumes:
  data:
    driver: local