# Neo4j Docker Compose
networks:
  schenet:
    external: true

volumes:
  neo4j1-data:
  neo4j1-logs:
  neo4j2-data:
  neo4j2-logs:
  neo4j3-data:
  neo4j3-logs:

services:
  neo4j1:
    image: neo4j:2025.08.0-enterprise
    container_name: neo4j1
    networks: [schenet]
    hostname: neo4j1
    ports:
      - "7474:7474"   # HTTP (Browser)
      - "7687:7687"   # Bolt
      - "6001:6000"   # Discovery (optional to expose)
      - "7001:7000"   # Raft (optional to expose)
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Basic auth (or use *_FILE with Docker secrets if you prefer)
      - NEO4J_AUTH=neo4j/neo4j_password

      # Cluster discovery endpoints (all servers)
      - NEO4J_dbms_cluster_endpoints=neo4j1:6000,neo4j2:6000,neo4j3:6000

      # Advertised addresses for this server
      - NEO4J_server_cluster_advertised__address=neo4j1:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j1:7000
      # - NEO4J_server_default_listen__address=0.0.0.0
      # - NEO4J_server__default__advertised____address=neo4j1
      - NEO4J_server_bolt_advertised__address=neo4j1:7687
      - NEO4J_server_http_advertised__address=neo4j1:7474

      # Optional tuning examples
      # - NEO4J_server_memory_pagecache_size=1G
      # - NEO4J_server_memory_heap_initial__size=1G
      # - NEO4J_server_memory_heap_max__size=2G

    volumes:
      - neo4j1-data:/data
      - neo4j1-logs:/logs
    restart: unless-stopped

  neo4j2:
    image: neo4j:2025.08.0-enterprise
    container_name: neo4j2
    networks: [schenet]
    hostname: neo4j2
    # Typically you only expose HTTP/Bolt on one node; uncomment if needed:
    # ports:
    #   - "7475:7474"
    #   - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_cluster_endpoints=neo4j1:6000,neo4j2:6000,neo4j3:6000
      - NEO4J_server_cluster_advertised__address=neo4j2:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j2:7000
      # - NEO4J_server_default_listen__address=0.0.0.0
      # - NEO4J_server__default__advertised____address=neo4j2
      - NEO4J_server_bolt_advertised__address=neo4j2:7687
      - NEO4J_server_http_advertised__address=neo4j2:7474
    volumes:
      - neo4j2-data:/data
      - neo4j2-logs:/logs
    restart: unless-stopped

  neo4j3:
    image: neo4j:2025.08.0-enterprise
    container_name: neo4j3
    networks: [schenet]
    hostname: neo4j3
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_cluster_endpoints=neo4j1:6000,neo4j2:6000,neo4j3:6000
      - NEO4J_server_cluster_advertised__address=neo4j3:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j3:7000
      # - NEO4J_server_default_listen__address=0.0.0.0
      # - NEO4J_server__default__advertised____address=neo4j3
      - NEO4J_server_bolt_advertised__address=neo4j3:7687
      - NEO4J_server_http_advertised__address=neo4j3:7474
    volumes:
      - neo4j3-data:/data
      - neo4j3-logs:/logs
    restart: unless-stopped
