services:
  batch-worker:
    image: batch-worker:dev
    platform: linux/arm64
    container_name: batch-worker
    build:
      context: ../..
      dockerfile: cmd/workers/batch/Dockerfile
      args:
        GO_VERSION: "1.23.6"
    env_file:
      - ../../env/batch.env
    volumes:
      - ../../cmd/workers/batch/creds:/app/creds:ro
      - ../../cmd/workers/batch/data:/app/data:ro
    restart: unless-stopped
    networks:
      schenet:

networks:
  schenet:
    external: true