version: '3.8'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: scheduler-mysql
    restart: always
    env_file:
      - mysql.env
    ports:
      - '3306:3306'
    volumes:
      - ${DATA_VOLUME}:/var/lib/mysql
      - ${INIT_SCRIPT_PATH}/:/docker-entrypoint-initdb.d/
    networks:
      - schenet

networks:
  schenet:
    driver: bridge
