# Single node MongoDB cluster
services:
  scheduler-mongo:
    image: mongo:8.0
    container_name: scheduler-mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "scheduler-mongo_data:/data/db"
      - "scheduler-mongo_config:/data/configdb"

volumes:
  scheduler-mongo_data:
  scheduler-mongo_config: